version: '3.7'

x-volumes: &volumes
  - .:/otrs-ce-installer

x-centos-volumes: &centos-volumes
  - .:/otrs-ce-installer
  - /sys/fs/cgroup:/sys/fs/cgroup:ro

services:
  # Alpine Linux 3
  test-alpine-3:
    image: alpine:3
    tty: true
    volumes: *volumes

  # CentOS 8
  test-centos-8: &test-centos-8
    build:
      context: &centos-8-context ./tests/centos-8
      target: base
    privileged: true
    tty: true
    volumes: *centos-volumes
  # CentOS 8 with Perl installed
  test-centos-8-stage-1:
    <<: *test-centos-8
    build:
      context: *centos-8-context
      target: stage-1
      cache_from: [ test-centos-8:latest ]
  # CentOS 8 with Perl and Apache installed
  test-centos-8-stage-2:
    <<: *test-centos-8
    build:
      context: *centos-8-context
      target: stage-2
      cache_from: [ test-centos-8-stage-1:latest ]
  # CentOS 8 with Perl, Apache and MariaDB installed
  test-centos-8-stage-3:
    <<: *test-centos-8
    build:
      context: *centos-8-context
      target: stage-3
      cache_from: [ test-centos-8-stage-2:latest ]
  # CentOS 8 with Perl, Apache, MariaDB and required Perl modules installed
  test-centos-8-stage-4:
    <<: *test-centos-8
    build:
      context: *centos-8-context
      target: stage-4
      cache_from: [ test-centos-8-stage-3:latest ]

  # Ubuntu 20.04
  test-ubuntu-20-04: &test-ubuntu-20-04
    build:
      context: &ubuntu-20-04-context ./tests/ubuntu-20-04
      target: base
    privileged: true
    tty: true
    volumes:
      *centos-volumes
  # Ubuntu 20.04 with Perl and Apache installed
  test-ubuntu-20-04-stage-1:
    <<: *test-ubuntu-20-04
    build:
      context: *ubuntu-20-04-context
      target: stage-1
      cache_from: [ test-ubuntu-20-04:latest ]
  # Ubuntu 20.04 with Perl, Apache and MariaDB installed
  test-ubuntu-20-04-stage-2:
    <<: *test-ubuntu-20-04
    build:
      context: *ubuntu-20-04-context
      target: stage-2
      cache_from: [ test-ubuntu-20-04-stage-1:latest ]
  # Ubuntu 20.04 with Perl, Apache, MariaDB and Perl modules installed
  test-ubuntu-20-04-stage-3:
    <<: *test-ubuntu-20-04
    build:
      context: *ubuntu-20-04-context
      target: stage-3
      cache_from: [ test-ubuntu-20-04-stage-2:latest ]
